version: '2'
services:
  server:
    environment:
      - 'POSTGRES_HOST=pg2'
      - 'POSTGRES_PORT=5432'
      - 'PORT=8080'
    image: 'stinni/tictactoe'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    links:
      - 'pg2'
  pg2:
    image: postgres
    ports:
      - "5432:5432"