version: '2'
services:
  server:
    image: stinni/tictactoe:${GIT_COMMIT}
    environment:
      - 'PORT=8080'
      - 'NODE_ENV=production'
    ports:
      - '8080:8080'
      - '80:3000'
    links:
      - 'pg2'
    depends_on:
      - 'pg2'
  pg2:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    ports:
      - '5432:5432'