version: '2'
services:
  server:
    environment:
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'PORT=3000'
    image: 'into-docker'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    links:
      - 'postgres'
  postgres:
    image: postgres
    ports:
      - "5432:5432"